# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c234915edc854b3d8f3d2ff20a442f7d30e454c3823188dcb3bbafc8a26ec758499976de75961d59a70e1ad65adb66115bee44a69b22831718acaa758cd96b0

test:
  secret_key_base: 606e0d996ef311b338d8b932050eee1fc9ec9cd2568d6945ed8c563795f234438de2f5eb4c02ce7bc49eb4517a43fb78fd0747a1dcaf0ac181ab07e885da60b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
